package by.epam.bokhan.dao.impl;


class DAOConstant {
    static final String ORDER_DATE = "orders.order_date";
    static final String ORDER_EXPIRATION_DATE = "orders.expiration_date";
    static final String ORDER_RETURN_DATE = "orders.return_date";
    static final String USER_NAME = "user.name";
    static final String USER_SURNAME = "user.surname";
    static final String USER_PATRONYMIC = "user.patronymic";
    static final String MOBILE_PHONE = "library_card.mobile_phone";
    static final String USER_ID = "user.id";
    static final String LIBRARY_CARD = "library_card.id";
    static final String BOOK_ID = "book.id";
    static final String AUTHOR_NAME = "author_name";
    static final String AUTHOR_SURNAME = "author_surname";
    static final String AUTHOR_PATRONYMIC = "author_patronymic";
    static final String BOOK_TITLE = "book.title";
    static final String BOOK_PAGES = "book.pages";
    static final String BOOK_ISBN = "book.isbn";
    static final String BOOK_YEAR = "book.year";
    static final String BOOK_DESCRIPTION = "book.description";
    static final String BOOK_LOCATION = "book.location";
    static final String PUBLISHER_ID = "publisher.id";
    static final String PUBLISHER_NAME = "publisher.name";
    static final String GENRES_NAME = "genre_name";
    static final String GENRES_ID = "genres.genre_id";
    static final String GENRE_NAME = "genre.name";
    static final String GENRE_ID = "genre.id";
    static final String AUTHOR_ID = "author.id";
    static final String AUTHOR_DATE_OF_BIRTH = "author.date_of_birth";
    static final String ORDER_ID = "orders.id";
    static final String ONLINE_ORDER_ID = "online_orders.id";
    static final String ONLINE_ORDER_STATUS = "online_orders.order_status";
    static final String ONLINE_ORDER_DATE_OF_ORDER = "online_orders.order_date";
    static final String ONLINE_ORDER_EXPIRATION_DATE = "online_orders.expiration_date";
    static final String ONLINE_ORDER_EXECUTION_DATE = "online_orders.order_execution_date";
    static final String ADDRESS = "address";
    static final String LOGIN = "login";
    static final String BLOCK_FIELD = "blocked";
    static final String PASSWORD = "password";
    static final String ROLE = "role.name";
    static final String ORDERS_BOOK_ID = "orders.book_id";
    static final String USER_PHOTO = "user.photo";
    static final int BLOCKED_VALUE = 1;
    static final int UNBLOCKED_VALUE = 0;
    static final int POSITIVE_RESULT_VALUE = 1;
    static final int FIRST_INDEX = 0;
    static final String BOOK_IMAGE = "book.image";
    static final String AUTHORS_ID = "author_id";
}
